// src/ClassTable.jsx
import range from 'lodash/range'
import React from 'react'
import { useParams } from 'react-router-dom'

import ClassBlock from './ClassBlock'
import { dayName, useLessonData } from './Utils'

export default ({ selectedLesson, colorMapping }) => {
  const { semester } = useParams()
  const { data: lessons } = useLessonData(semester)
  if (lessons) {
    const selectedLessonObjects = lessons.filter((lesson) =>
      selectedLesson.has(lesson.jxbmc)
    )
    let colMax = 5
    selectedLessonObjects.forEach((lesson) => {
      if (lesson.xqj > 5) {
        colMax = 7
      }
    })
    const allCol = range(1, colMax + 1)
    return (
      <table className='table classtable-table'>
        <thead>
          <tr>
            <th scope='col' className='classtable-first-col'>
              #
            </th>
            {allCol.map((n, lessonCol) => (
              <th scope='col' key={lessonCol} className='classtable-col'>
                {dayName[lessonCol]}
              </th>
            ))}
          </tr>
        </thead>
        <tbody>
          {range(1, 15).map((lessonRow) => (
            <tr v-for='lessonRow in 14' key={lessonRow}>
              <th scope='row' className='classtable-first-col p-1'>
                {lessonRow}
              </th>
              {allCol.map((lessonCol) => (
                <td scope='col' key={lessonCol} className='p-1'>
                  <ClassBlock
                    day={lessonCol}
                    block={lessonRow}
                    selectedLesson={selectedLessonObjects}
                    colorMapping={colorMapping}
                  ></ClassBlock>
                </td>
              ))}
            </tr>
          ))}
        </tbody>
      </table>
    )
  } else {
    return <div></div>
  }
}

// src/components/ClassTable.vue
<template>
  <div class="h-100 overflow-auto">
    <table class="table classtable-table">
      <thead>
        <tr>
          <th scope="col" class="classtable-first-col">#</th>
          <th scope="col" v-for="(n, lessonCol) in allCol" :key="lessonCol">
            {{ dayName[lessonCol] }}
          </th>
        </tr>
      </thead>
      <tbody>
        <tr v-for="lessonRow in 14" :key="lessonRow">
          <th scope="row" class="classtable-first-col p-1">{{ lessonRow }}</th>
          <td v-for="lessonCol in allCol" :key="lessonCol" class="p-1">
            <ClassBlock
              :day="lessonCol"
              :block="lessonRow"
              :lessonData="lessons"
              :mappingData="allMapping"
              :colorMapping="colorMapping"
              :classTableConfig="classTableConfig"
              :lessonDetail="lessonDetail"
            ></ClassBlock>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</template>

<script lang="ts">
import { Component, Vue, Prop } from "vue-property-decorator";
import {
  Lesson,
  ClassTableMapping,
  ClassTableConfig,
  LessonDetail,
  mappingOf,
  dayName
} from "@/models";
import ClassBlock from "@/components/ClassBlock.vue";

@Component({
  components: { ClassBlock }
})
export default class ClassTable extends Vue {
  mappingOf = mappingOf;

  dayName = dayName;

  @Prop() lessons!: Lesson[];

  @Prop() private lessonDetail!: { [id: string]: LessonDetail };

  @Prop() classTableConfig!: ClassTableConfig;

  @Prop() private colorMapping!: { [id: string]: string };

  get allMapping() {
    const mm: { [id: string]: ClassTableMapping } = {};
    this.lessons.forEach(lesson => {
      const mapping = this.mappingOf(lesson);
      if (!(lesson.jxb_id in mm)) mm[lesson.jxb_id] = {};
      for (const key in mapping) {
        mm[lesson.jxb_id][key] = mm[lesson.jxb_id][key] || mapping[key];
      }
    });

    return mm;
  }

  get allCol() {
    let result = 5;
    this.lessons.forEach(lesson => {
      if (lesson.xqj > 5) {
        result = 7;
      }
    });
    return result;
  }
}
</script>

<style scoped lang="scss">
.classtable-row {
  min-height: 6.5vh;
  border-bottom: 0.1px dashed grey;
}

.classtable-table {
  table-layout: fixed;
}

.classtable-first-col {
  width: 2rem !important;
}
</style>
